name: 'pluto'
version: '1.0.0'
config-version: 2

profile: 'pluto'


source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"


seeds:
    +schema: seed_data
