name: 'dbtplyr_integration_tests'
version: '1.0'

profile: 'dbtplyr'

# require-dbt-version: inherit this from dbt-utils

config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

seeds:
  +quote_columns: true